apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: loginapp
  ports:
    - port: 80        # Service port
      targetPort: 80  # Container port
      nodePort: 30080 # Access via EC2 public IP:30080
